#!/usr/bin/env groovy
pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {image 'mave'}
            }
            steps {
                sh "mvn package -Dmaven.teste.skip=true"
            }
        }
    }
}