#!/usr/bin/env groovy
pipeline {
    agent {
        docker {
            image 'maven'

        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }

        stage('Unit Test') { 
            agent {
                docker {
                image 'mysql'
                args '--name some-mysql -e MYSQL_ROOT_PASSWORD=root -d'}
            }
            steps {
               sh "mvn package -Dmaven.test.skip=true"
            }
        }
    }
}
