#!/usr/bin/env groovy
pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {image 'maven'}
            }
            steps {
                sh "docker-compose up"
                sh "mvn package -Dmaven.teste.skip=true"
            }
        }
    }
}
